repos:
  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: stylelint --fix --config .styleintrc.json
        language: node
        types: [css]
        additional_dependencies:
          - stylelint@16.21.0
          - stylelint-config-standard@38.0.0 
          - "@stylistic/stylelint-config@2.0.0"
          - "@stylistic/stylelint-plugin@3.1.2"
          - postcss@8.5.6